version: '3'

services:
  nginx:
    image: nginx
    restart: always
    ports:
      - "1488:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # исправлено путь к конфигурационному файлу
      - ./static-website/:/usr/share/nginx/html:ro  # указываем стандартное место для статических файлов




